"""empty message

Revision ID: 576c4379ff72
Revises: ef1fc9ee6813
Create Date: 2020-01-03 06:01:27.646997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576c4379ff72'
down_revision = 'ef1fc9ee6813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
